/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IMasterChefV3 } from "../IMasterChefV3";

export class IMasterChefV3__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMasterChefV3 {
    return new Contract(address, _abi, signerOrProvider) as IMasterChefV3;
  }
}

const _abi = [
  {
    inputs: [],
    name: "nonfungiblePositionManager",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "skyxPerSecond",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_v3Pool",
        type: "address",
      },
    ],
    name: "skyxPerSecondByPool",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
