/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ISkyXV3LmPool } from "../ISkyXV3LmPool";

export class ISkyXV3LmPool__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISkyXV3LmPool {
    return new Contract(address, _abi, signerOrProvider) as ISkyXV3LmPool;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "currTimestamp",
        type: "uint32",
      },
    ],
    name: "accumulateReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int24",
        name: "tick",
        type: "int24",
      },
      {
        internalType: "bool",
        name: "zeroForOne",
        type: "bool",
      },
    ],
    name: "crossLmTick",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
