/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ISkyXV3LmPoolDeployer } from "../ISkyXV3LmPoolDeployer";

export class ISkyXV3LmPoolDeployer__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISkyXV3LmPoolDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISkyXV3LmPoolDeployer;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ISkyXV3Pool",
        name: "pool",
        type: "address",
      },
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "contract ILMPool",
        name: "lmPool",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
