/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ISkyXV3LmPoolInterface extends ethers.utils.Interface {
  functions: {
    "accumulateReward(uint32)": FunctionFragment;
    "crossLmTick(int24,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "accumulateReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "crossLmTick",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "accumulateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "crossLmTick",
    data: BytesLike
  ): Result;

  events: {};
}

export class ISkyXV3LmPool extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ISkyXV3LmPoolInterface;

  functions: {
    accumulateReward(
      currTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "accumulateReward(uint32)"(
      currTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    crossLmTick(
      tick: BigNumberish,
      zeroForOne: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "crossLmTick(int24,bool)"(
      tick: BigNumberish,
      zeroForOne: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  accumulateReward(
    currTimestamp: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "accumulateReward(uint32)"(
    currTimestamp: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  crossLmTick(
    tick: BigNumberish,
    zeroForOne: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "crossLmTick(int24,bool)"(
    tick: BigNumberish,
    zeroForOne: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    accumulateReward(
      currTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "accumulateReward(uint32)"(
      currTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    crossLmTick(
      tick: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "crossLmTick(int24,bool)"(
      tick: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    accumulateReward(
      currTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "accumulateReward(uint32)"(
      currTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    crossLmTick(
      tick: BigNumberish,
      zeroForOne: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "crossLmTick(int24,bool)"(
      tick: BigNumberish,
      zeroForOne: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accumulateReward(
      currTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "accumulateReward(uint32)"(
      currTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    crossLmTick(
      tick: BigNumberish,
      zeroForOne: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "crossLmTick(int24,bool)"(
      tick: BigNumberish,
      zeroForOne: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
