/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ISkyXV3LmPoolDeveloperInterface extends ethers.utils.Interface {
  functions: {
    "parameters()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "parameters",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "parameters", data: BytesLike): Result;

  events: {};
}

export class ISkyXV3LmPoolDeveloper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ISkyXV3LmPoolDeveloperInterface;

  functions: {
    parameters(
      overrides?: CallOverrides
    ): Promise<[string, string] & { pool: string; masterChef: string }>;

    "parameters()"(
      overrides?: CallOverrides
    ): Promise<[string, string] & { pool: string; masterChef: string }>;
  };

  parameters(
    overrides?: CallOverrides
  ): Promise<[string, string] & { pool: string; masterChef: string }>;

  "parameters()"(
    overrides?: CallOverrides
  ): Promise<[string, string] & { pool: string; masterChef: string }>;

  callStatic: {
    parameters(
      overrides?: CallOverrides
    ): Promise<[string, string] & { pool: string; masterChef: string }>;

    "parameters()"(
      overrides?: CallOverrides
    ): Promise<[string, string] & { pool: string; masterChef: string }>;
  };

  filters: {};

  estimateGas: {
    parameters(overrides?: CallOverrides): Promise<BigNumber>;

    "parameters()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    parameters(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "parameters()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
