/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SkyXV3PoolDeployerInterface extends ethers.utils.Interface {
  functions: {
    "deploy(address,address,address,uint24,int24)": FunctionFragment;
    "factoryAddress()": FunctionFragment;
    "parameters()": FunctionFragment;
    "poolInitCodeHash()": FunctionFragment;
    "setFactoryAddress(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deploy",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "factoryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "parameters",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolInitCodeHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFactoryAddress",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "factoryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "parameters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolInitCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFactoryAddress",
    data: BytesLike
  ): Result;

  events: {
    "SetFactoryAddress(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SetFactoryAddress"): EventFragment;
}

export class SkyXV3PoolDeployer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SkyXV3PoolDeployerInterface;

  functions: {
    deploy(
      factory: string,
      token0: string,
      token1: string,
      fee: BigNumberish,
      tickSpacing: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deploy(address,address,address,uint24,int24)"(
      factory: string,
      token0: string,
      token1: string,
      fee: BigNumberish,
      tickSpacing: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    factoryAddress(overrides?: CallOverrides): Promise<[string]>;

    "factoryAddress()"(overrides?: CallOverrides): Promise<[string]>;

    parameters(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, number, number] & {
        factory: string;
        token0: string;
        token1: string;
        fee: number;
        tickSpacing: number;
      }
    >;

    "parameters()"(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, number, number] & {
        factory: string;
        token0: string;
        token1: string;
        fee: number;
        tickSpacing: number;
      }
    >;

    poolInitCodeHash(overrides?: CallOverrides): Promise<[string]>;

    "poolInitCodeHash()"(overrides?: CallOverrides): Promise<[string]>;

    setFactoryAddress(
      _factoryAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setFactoryAddress(address)"(
      _factoryAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  deploy(
    factory: string,
    token0: string,
    token1: string,
    fee: BigNumberish,
    tickSpacing: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deploy(address,address,address,uint24,int24)"(
    factory: string,
    token0: string,
    token1: string,
    fee: BigNumberish,
    tickSpacing: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  factoryAddress(overrides?: CallOverrides): Promise<string>;

  "factoryAddress()"(overrides?: CallOverrides): Promise<string>;

  parameters(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, number, number] & {
      factory: string;
      token0: string;
      token1: string;
      fee: number;
      tickSpacing: number;
    }
  >;

  "parameters()"(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, number, number] & {
      factory: string;
      token0: string;
      token1: string;
      fee: number;
      tickSpacing: number;
    }
  >;

  poolInitCodeHash(overrides?: CallOverrides): Promise<string>;

  "poolInitCodeHash()"(overrides?: CallOverrides): Promise<string>;

  setFactoryAddress(
    _factoryAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setFactoryAddress(address)"(
    _factoryAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    deploy(
      factory: string,
      token0: string,
      token1: string,
      fee: BigNumberish,
      tickSpacing: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "deploy(address,address,address,uint24,int24)"(
      factory: string,
      token0: string,
      token1: string,
      fee: BigNumberish,
      tickSpacing: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    factoryAddress(overrides?: CallOverrides): Promise<string>;

    "factoryAddress()"(overrides?: CallOverrides): Promise<string>;

    parameters(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, number, number] & {
        factory: string;
        token0: string;
        token1: string;
        fee: number;
        tickSpacing: number;
      }
    >;

    "parameters()"(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, number, number] & {
        factory: string;
        token0: string;
        token1: string;
        fee: number;
        tickSpacing: number;
      }
    >;

    poolInitCodeHash(overrides?: CallOverrides): Promise<string>;

    "poolInitCodeHash()"(overrides?: CallOverrides): Promise<string>;

    setFactoryAddress(
      _factoryAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setFactoryAddress(address)"(
      _factoryAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    SetFactoryAddress(factory: string | null): EventFilter;
  };

  estimateGas: {
    deploy(
      factory: string,
      token0: string,
      token1: string,
      fee: BigNumberish,
      tickSpacing: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "deploy(address,address,address,uint24,int24)"(
      factory: string,
      token0: string,
      token1: string,
      fee: BigNumberish,
      tickSpacing: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    factoryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "factoryAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    parameters(overrides?: CallOverrides): Promise<BigNumber>;

    "parameters()"(overrides?: CallOverrides): Promise<BigNumber>;

    poolInitCodeHash(overrides?: CallOverrides): Promise<BigNumber>;

    "poolInitCodeHash()"(overrides?: CallOverrides): Promise<BigNumber>;

    setFactoryAddress(
      _factoryAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setFactoryAddress(address)"(
      _factoryAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deploy(
      factory: string,
      token0: string,
      token1: string,
      fee: BigNumberish,
      tickSpacing: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deploy(address,address,address,uint24,int24)"(
      factory: string,
      token0: string,
      token1: string,
      fee: BigNumberish,
      tickSpacing: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    factoryAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "factoryAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parameters(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "parameters()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolInitCodeHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "poolInitCodeHash()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFactoryAddress(
      _factoryAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setFactoryAddress(address)"(
      _factoryAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
